# Generated by Django 5.1.6 on 2025-02-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='event_type',
            field=models.CharField(choices=[('wedding', 'Wedding'), ('birthday', 'Birthday'), ('corporate', 'Corporate Event'), ('engagement', 'Engagement'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
