# Generated by Django 5.1.6 on 2025-02-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0002_eventbooking_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='menu_items',
            field=models.ManyToManyField(to='catering.menu'),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
