# Generated by Django 5.1.6 on 2025-03-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0006_eventbooking_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbooking',
            name='event_date',
            field=models.DateTimeField(unique=True),
        ),
    ]
